spring:
 profiles:
  active:
  - dev
---
server:
 port: 8001

spring:
 profiles: dev
 application:
  name: microservicecloud-config-dept-client
 datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

eureka:
  client: # 客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-config-dept8001 #注册到eureka中的实例名
    prefer-ip-address: true # 访问路径可以显示ip地址


info:
  app.name: atguigu-microservicecloud-config
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}  #这里按照视频中的$project.artifactId$不能获取到值
  build.version: ${project.version}
---
server:
 port: 8002

spring:
 profiles: test
 application:
  name: microservicecloud-config-dept-client
 datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

eureka:
  client: # 客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-config-dept8002 #注册到eureka中的实例名
    prefer-ip-address: true # 访问路径可以显示ip地址


info:
  app.name: atguigu-microservicecloud-config
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}  #这里按照视频中的$project.artifactId$不能获取到值
  build.version: ${project.version}

  